server.port=8081
spring.application.name=user-service

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/parking_user_db
spring.datasource.username=postgres
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/